<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.example.sample.CalculationTest" tests="5" skipped="0" failures="0" errors="0" timestamp="2023-08-04T11:15:39" hostname="DESKTOP-P5GE5IL" time="0.012">
  <properties/>
  <testcase name="잘못된_연산자가_들어오면_에러가_난다()" classname="com.example.sample.CalculationTest" time="0.003"/>
  <testcase name="나눗셈_연산을_할_수_있다()" classname="com.example.sample.CalculationTest" time="0.002"/>
  <testcase name="뺄셈_연산을_할_수_있다()" classname="com.example.sample.CalculationTest" time="0.001"/>
  <testcase name="곱셈_연산을_할_수_있다()" classname="com.example.sample.CalculationTest" time="0.001"/>
  <testcase name="덧셈_연산을_할_수_있다()" classname="com.example.sample.CalculationTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
